import Head from "next/head";
import ContactForm from "@/components/ContactForm";

/* =====================
   Home Page
====================== */
export default function Home() {
  return (
    <>
      {/* =====================
          SEO & Meta
      ====================== */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* =====================
          Page Content
      ====================== */}
      <ContactForm />
    </>
  );
}
